// Brandon P. Kyriss
// CS 362_400
// Quiz 2

#include<string.h>
#include<stdlib.h>
#include<time.h>

char iString[6];

char inputChar()
{
    // Randomly return one of the possible printable ASCII chars
    return rand() % (126 - 32 + 1) + 32; 
}

/*
char *inputString()
{
    int i;

    for(i = 0; i < 5; i++)
    {
      // Set each character in the array to a lowercase ASCII char between a and z (26 letters)
      iString[i] = 'a' + (random() % 26);
    }

    // Terminate the string
    iString[5] = '\0'; 
    return iString;

}
*/


char *inputString()
{
  int i;
 
  // 30 chars (26 + 4) r,s,t,e are 2x more likely to occur
  char chars[] = {'a','b','c','d','e','e','f','g','h','i','j','k','l','m','n','o','p',
                  'q','r','r','s','s','t','t','u','v','w','x','y','z'};
                  
  for(i = 0; i < 5; i++)
  {
    // Set each character in the array to a lowercase ASCII char between a and z (26 letters)
    iString[i] = chars[rand() % (30)];
  }
    // Terminate the string
    iString[5] = '\0'; 
    return iString;
}


void testme()
{
  int tcCount = 0;
  char *s;
  char c;
  int state = 0;
  while (1)
  {
    tcCount++;
    c = inputChar();
    s = inputString();
    printf("Iteration %d: c = %c, s = %s, state = %d\n", tcCount, c, s, state);

    // Ok, we error out when the state has been set to 9 and the string == reset\0 <-- (must correctly terminate string)
    // To get to state == 9, we must make it through each previous state (0 - 8) by entering the required char for
    // each stage (randomly generated by inputChar(). So, we need to randomly generate ASCII set chars (128) for inputChar()
    // and randomly generate a \0 - terminated string of 5 ASCII characters between 'a' and 'z'
    if (c == '[' && state == 0) state = 1;
    if (c == '(' && state == 1) state = 2;
    if (c == '{' && state == 2) state = 3;
    if (c == ' '&& state == 3) state = 4;
    if (c == 'a' && state == 4) state = 5;
    if (c == 'x' && state == 5) state = 6;
    if (c == '}' && state == 6) state = 7;
    if (c == ')' && state == 7) state = 8;
    if (c == ']' && state == 8) state = 9;
    if (s[0] == 'r' && s[1] == 'e'
       && s[2] == 's' && s[3] == 'e'
       && s[4] == 't' && s[5] == '\0'
       && state == 9)
    {
      printf("error ");
      exit(200);
    }
  }
}


int main(int argc, char *argv[])
{
    srand(time(NULL));
    testme();
    return 0;
}
